docs: add svelte guide
fontsource/fontsource pull request #575
Opened 2022-09-19 08:23 UTC by vicentematus

- Add Svelte / Svelte Kit guide

Basically it's the same steps for both. 

Can you double check the `docsList.json`? Thanks 👍

2022-10-02 11:07 UTC, ayuhito requested changes
Thanks for submitting this PR! I'm planning to rewrite the entire docs with the new website design, but this serves as a great base. Thank you!

2022-10-02 11:07 UTC, ayuhito commented on website/docs/guides/sveltejs.mdx
> +```
I think it might be better to remove this section.

2022-10-02 11:07 UTC, ayuhito commented on website/docs/guides/sveltejs.mdx
> +And we are done 👍.
And remove this too :)

2022-10-09 00:07 UTC, vicentematus commented
Updated @ayuhito  👍. Can you check please !

2022-10-09 00:38 UTC, ayuhito approved these changes

2022-10-09 00:38 UTC, ayuhito commented
Looks great! Thank you for contributing!

2022-10-09 00:38 UTC, merged