Add uncut-sans font
fontsource/fontsource pull request #623
Opened 2023-01-13 14:30 UTC by lumoe

PR for Issue: https://github.com/fontsource/fontsource/issues/622

### Font Name

Uncut Sans

### Link to font source

https://github.com/kaspernordkvist/uncut_sans/

### Link to font license

https://github.com/kaspernordkvist/uncut_sans/blob/main/LICENSE.txt

2023-01-13 20:59 UTC, lumoe commented
I am not entirely sure why the Vercel deployment fails, I also cannot lookup the details in the log.  

Any insights if my PR contains any mistakes?

2023-01-13 21:07 UTC, jwr12135 commented
You can ignore vercel, it's only used for previewing website changes.

2023-01-18 10:14 UTC, ayuhito requested changes

2023-01-18 10:14 UTC, ayuhito commented on fonts/other/uncut-sans/files/rename.py
> +import os
Looks good to me! I just think we need to remove this one file and we should be good to go!

2023-01-18 10:27 UTC, lumoe commented
Removed the file. Thank you for having a look at it!

2023-01-18 10:31 UTC, ayuhito approved these changes

2023-01-18 10:32 UTC, ayuhito commented
Thanks for the PR! You should see the changes published within an hour.

2023-01-18 10:32 UTC, merged