fix(cli): remove displayVar option from sass mixins
fontsource/fontsource pull request #754
Opened 2023-06-04 00:39 UTC by jwr1

This follows #751.

2023-06-06 20:37 UTC, ayuhito requested changes
LGTM! I think we need to update the website documentation, but other than that everything seems fine to me.

2023-06-06 23:42 UTC, jwr1 commented
Should we remove the [Font Display](https://fontsource.org/docs/getting-started/display) page from the documentation as well? Maybe in a separate pull request?

2023-06-07 12:48 UTC, ayuhito commented
> Should we remove the [Font Display](https://fontsource.org/docs/getting-started/display) page from the documentation as well? Maybe in a separate pull request?

I think we'll update that separately. I have an idea which may keep the guide with a separate solution requiring you to write your own `@font-face` selectors. Does need testing to verify it works though.

2023-06-07 12:48 UTC, ayuhito approved these changes

2023-06-07 12:49 UTC, merged